mod 'boxen',    '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib',   '4.1.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'homebrew', '1.1.2', :github_tarball => 'boxen/puppet-homebrew'
mod 'java',     '1.1.0', :github_tarball => 'boxen/puppet-java'